### ISSUE TITLE
Sparse nllb model too large

### ISSUE THREAD

**Issue by Dimildizio** [Ekaterina-Sinkova/SciTranslate#10]
Couldn't load it on my google colab (had 20gb free)
If anyone has more **disk** space, plz run create_translations.ipynb and provide a new dataset with one more column for big sparse model translations

**Comment by Ekaterina-Sinkova** [comment]
Generating with NLLB-MoE
The avalable checkpoints requires around 350GB of storage. Make sure to use accelerate if you do not have enough RAM on your machine.
