### ISSUE TITLE
NLLB model seems to be pretty slow

### ISSUE THREAD

**Issue by Dimildizio** [Ekaterina-Sinkova/SciTranslate#16]
**Describe the issue** 
On inference creating a NLLB model takes plenty of time so as of now it is created once at the start of the session.
(Also further action should be taken to speed up the performance of the model. NLLB loses miserably to google translate in speed on inference.)

        There could possibly be an issue if we were to increase the scope of the project
        Currently the output language is English with no other options
        To increase inference speed the translator model is created only once when the instance of UI is created
        We should contemplate on when to create model in case changing the language feature gets implemented

**Comment by Ekaterina-Sinkova** [comment]
Должно полечиться на инференсе на гпу
